// <auto-generated />
namespace Academia.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class se_agrego_campo_nuevo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(se_agrego_campo_nuevo));
        
        string IMigrationMetadata.Id
        {
            get { return "202108182307541_se_agrego_campo_nuevo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
